version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./mnt:/var/mnt
    command: /var/app/run.sh
