
version: "3.7"
services:
  admin-daemon:
    build:
      context: ./admin-daemon
      dockerfile: Dockerfile
    tty: true
    # ports:
    #   - 8080:8080
    environment:
      TZ: Asia/Tokyo
      DEVELOP: "1"
    volumes:
      - ./admin-daemon:/var/app
    # command: python3 /var/app/main.py
