version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: mq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/home:/var/lib/rabbitmq
      - ./rabbitmq/config:/etc/rabbitmq/conf.d
    environment:
      RABBITMQ_DEFAULT_USER: system
      RABBITMQ_DEFAULT_PASS: system
